---
workflow:
  rules:
    - changes:
      - 'docker-compose/**/*'
      when: always
    - when: never

stages:
  - build

execute_script:
  stage: build
  tags:
    - linux
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  script:
    - echo "Running VM images build script..."
    - cd /data/vmimagebuilder
    - ./almaimage.sh
    - echo "VM images were built and uploaded to https://images.vereign.io/staging/"
    - curl -X POST "https://gitlab.hin-infra.ch/api/v4/projects/336/trigger/pipeline" -F token=glptt-_woePGXry2V7ZBNiETRB -F ref=main
