name: documentation

on:
  push:
    branches:
      - main

permissions:
  contents: write
  id-token: write
  pages: write

jobs:
  documentation:
    name: Build documentation
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build documentation
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/docs \
            squidfunk/mkdocs-material build --clean

      - name: Adjust permissions
        run: |
          chmod -c -R +rX site/ | while read line; do
            echo "::warning title=Invalid file permissions automatically fixed::$line"
          done

      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4